# stops are written as "name, address"
# routes start and end at the same location for convenience
12th man:
- MSC - 12th Man, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel - 12th Man, A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Wehner - 12th Man - Outbound, 4113 TAMU, College Station, TX 77845
- Vet School - Outbound, Veterinary & Biomedical Education Complex, 660 Raymond Stotzer Pkwy, College Station, TX 77843
- Transit - Outbound, 969 Agronomy Rd, College Station, TX 77840
- Facilities Services - Outbound, Physical Plant Adminstration & Shops, 600 Agronomy Rd, College Station, TX 77840
- GSC, 750 Agronomy Rd, College Station, TX 77840
- Facilities Services - Inbound, Physical Plant Adminstration & Shops, 600 Agronomy Rd, College Station, TX 77840
- Transit - Inbound, 969 Agronomy Rd, College Station, TX 77840
- Lot 71, 230 Agronomy Rd, College Station, TX 77840
- Vet School - Inbound, Veterinary & Biomedical Education Complex, 660 Raymond Stotzer Pkwy, College Station, TX 77843
- Wehner - Inbound, 4113 TAMU, College Station, TX 77845


Bonfire:
- Commons, 676 Lubbock St, College Station, TX 77840
- Ross and Bizzell - Bonfire - North, Ross Street & Bizzell Street, College Station, TX 77840
- Ross and Ireland - Bonfire - North, Ross Street & Ireland Street, College Station, TX 77840
- Asbury Water Tower - Bonfire, 191 Asbury St, College Station, TX 77840
- HEEP, 474 Olsen Blvd, College Station, TX 77845
- Kleberg - Bonfire - Outbound, Kleberg Center, College Station, TX 77845
- Rec Center - Bonfire, 187 Corrington Dr, College Station, TX 77843
- Lot 100 G, Tom Chandler Dr, College Station, TX 77840
- Reed Arena - Bonfire, 730 Olsen Blvd, College Station, TX 77843
- Kleberg - Bonfire - Inbound, Kleberg Center, College Station, TX 77845
- MSC - Bonfire, 215 Lamar St, College Station, TX 77844
- Fish Pond - Bonfire, Military Walk, College Station, TX 77840
- Ross and Ireland - Bonfire - South, Ross Street & Ireland Street, College Station, TX 77840
- Ross and Bizzell - Bonfire - South, North, Ross Street & Bizzell Street, College Station, TX 77840
- Southside Rec Center, 633 Bizzell St, College Station, TX 77843
- Lewis Street, Lewis Street, College Station, TX 77840
Bush School:
- MSC - Bush School, 275 Joe Routt Blvd, College Station, TX 77840
- Kleberg - Bush School - Outbound, Kleberg Center, College Station, TX 77845
- Reed Arena/Lot 97 - Bush School - Outbound, 730 Olsen Blvd, College Station, TX 77843
- Ag Building - Outbound, Ag Building - Bus Stop 524, College Station, TX
- GGB - Outbound, 2929 Research Pkwy, College Station, TX 77845
- Bush School - Outbound  , 4220 TAMU, College Station, TX 77845
- GERB, 1617 Research Pkwy, College Station, TX 77845
- Lot 108/UPD, 1115 Research Pkwy, College Station, TX 77845
- Technology Loop, Technology Loop, College Station, TX 77845
- Lot 41/43, 2450 Research Pkwy, College Station, TX 77840
- Bush School - Inbound, 4220 TAMU, College Station, TX 77845
- GGB - Inbound, 2929 Research Pkwy, College Station, TX 77845
- Ag Building - Inbound, Ag Building - Bus Stop 524, College Station, TX
- Reed Arena - Bush School - Inbound, 730 Olsen Blvd, College Station, TX 77843
- Kleberg - Bush School - Inbound, Kleberg Center, College Station, TX 77845
- MSC - ILCB, 215 Lamar St, College Station, TX 77844
Gig Em:
- Asbury Water Tower - Gig Em, 191 Asbury St, College Station, TX 77840
- Fish Pond - Gig Em, Military Walk, College Station, TX 77840
- Ross and Ireland - Gig Em - South, Ross Street & Ireland Street, College Station, TX 77840
- Ross and Bizzell - Gig Em - South, Ross Street & Bizzell Street, College Station, TX 77840
- Wisenbaker - East, 188 Bizzell St, College Station, TX 77801
- The Gardens, 578 John Kimbrough Blvd, College Station, TX 77845
- Becky Gates Center, 1125 Hensel Dr, College Station, TX 77840
- Hensel @ Texas, 502 College Ave, College Station, TX 77840
- Zachry, 125 Spence St, College Station, TX 77843
- Ross and Bizzell - Gig Em - North, Ross Street & Bizzell Street, College Station, TX 77840
- Ross and Ireland - Gig Em - North, Ross Street & Ireland Street, College Station, TX 77840
Howdy:
- MSC - Howdy, College Station, TX 77840
- Beutel - Howdy, A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Kleberg - Howdy - Outbound, College Station, TX 77845
- Reed Arena/Lot 97 - Howdy, 420 John Kimbrough Blvd, College Station, TX 77845
- Physical Education, 632 Penberthy Blvd, College Station, TX 77843
- Park West, 503 George Bush Dr W, College Station, TX 77840
- Olsen Field @ Blue Bell Park, 301 Olsen Blvd, College Station, TX 77840
- Rec Center - Howdy, 187 Corrington Dr, College Station, TX 77843
- Kleberg - Howdy - Inbound, Kleberg Center, College Station, TX 77845
Yell Practice:
- MSC - Yell Practice, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel - Yell Practice, A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Wehner - Yell Practice - Outbound, 4113 TAMU, College Station, TX 77845
- School of Public Health - Outbound, 212 Adriance Lab Rd, College Station, TX 77843
- White Creek 1, 225 Discovery Dr, College Station, TX 77845
- White Creek 2, 225 Discovery Dr, College Station, TX 77845
- Lot 101, 179 Discovery Dr, College Station, TX 77845
- NCTM, 100 Discovery Dr, College Station, TX 77845
- VTED, 800 Raymond Stotzer Pkwy, College Station, TX 77845
- Houston Building, 200 Discovery Dr, College Station, TX 77845
- White Creek Community Center, 667 W Campus Blvd, College Station, TX 77840
- School of Public Health - Inbound, 212 Adriance Lab Rd, College Station, TX 77843
- Wehner - Yell Practice - Inbound, 4113 TAMU, College Station, TX 77845
