# stops are written as "name, address"
# routes start and end at the same location for convenience
12th man:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel, A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Wehner, 4113 TAMU, College Station, TX 77845
- Vet School, Veterinary & Biomedical Education Complex, 660 Raymond Stotzer Pkwy, College Station, TX 77843
- Transit, 969 Agronomy Rd, College Station, TX 77840
- Facilities Services, Physical Plant Adminstration & Shops, 600 Agronomy Rd, College Station, TX 77840
- GSC, 750 Agronomy Rd, College Station, TX 77840
- Facilities Services, Physical Plant Adminstration & Shops, 600 Agronomy Rd, College Station, TX 77840
- Transit, 969 Agronomy Rd, College Station, TX 77840
- Lot 71, 230 Agronomy Rd, College Station, TX 77840
- Vet School, Veterinary & Biomedical Education Complex, 660 Raymond Stotzer Pkwy, College Station, TX 77843
- Wehner, 4113 TAMU, College Station, TX 77845
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
Bonfire:
- Commons, 676 Lubbock St, College Station, TX 77840
- Ross and Bizzell - North, Ross Street & Bizzell Street, College Station, TX 77840
- Ross and Ireland - North, Ross Street & Ireland Street, College Station, TX 77840
- Asbury Water Tower, 191 Asbury St, College Station, TX 77840
- Kleberg, Kleberg Center, College Station, TX 77845
- Rec Center, 187 Corrington Dr, College Station, TX 77843
- Lot 100 G, Tom Chandler Dr, College Station, TX 77840
- Reed Arena, 730 Olsen Blvd, College Station, TX 77843
- Kleberg, Kleberg Center, College Station, TX 77845
- MSC - ILCB, 215 Lamar St, College Station, TX 77844
- Fish Pond, Military Walk, College Station, TX 77840
- Ross and Ireland (South), Ross Street & Ireland Street, College Station, TX 77840
- Ross and Bizzell (South), North, Ross Street & Bizzell Street, College Station, TX 77840
- Southside Rec Center, 633 Bizzell St, College Station, TX 77843
- Lewis Street, Lewis Street, College Station, TX 77840
- Commons, 676 Lubbock St, College Station, TX 77840
Bush School:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Kleberg, Kleberg Center, College Station, TX 77845
- Reed Arena/Lot 97, 730 Olsen Blvd, College Station, TX 77843
- Ag Building, Ag Building - Bus Stop 524, College Station, TX
- GGB, 2929 Research Pkwy, College Station, TX 77845
- Bush School, 4220 TAMU, College Station, TX 77845
- GERB, 1617 Research Pkwy, College Station, TX 77845
- Lot 108/UPD, 1115 Research Pkwy, College Station, TX 77845
- Technology Loop, Technology Loop, College Station, TX 77845
- Lot 41/43, 2450 Research Pkwy, College Station, TX 77840
- Bush School 0 Inbound, 4220 TAMU, College Station, TX 77845
- GGB, 2929 Research Pkwy, College Station, TX 77845
- Ag Building, Ag Building - Bus Stop 524, College Station, TX
- Reed Arena, 730 Olsen Blvd, College Station, TX 77843
- Kleberg, Kleberg Center, College Station, TX 77845
- MSC - ILCB, 215 Lamar St, College Station, TX 77844
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
Gig Em:
- Asbury Water Tower, 191 Asbury St, College Station, TX 77840
- Fish Pond, Military Walk, College Station, TX 77840
- Ross and Ireland - South, Ross Street & Ireland Street, College Station, TX 77840
- Ross and Bizzell - South, Ross Street & Bizzell Street, College Station, TX 77840
- Wisenbaker - East, 188 Bizzell St, College Station, TX 77801
- The Gardens, 578 John Kimbrough Blvd, College Station, TX 77845
- Becky Gates Center, 1125 Hensel Dr, College Station, TX 77840
- Hensel @ Texas, 502 College Ave, College Station, TX 77840
- Zachry, 125 Spence St, College Station, TX 77843
- Ross and Bizzell - North, Ross Street & Bizzell Street, College Station, TX 77840
- Ross and Ireland - North, Ross Street & Ireland Street, College Station, TX 77840
- Asbury Water Tower, 191 Asbury St, College Station, TX 77840
Howdy:
- MSC Bus Stop, College Station, TX 77840
- A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Kleberg Center, College Station, TX 77845
- 420 John Kimbrough Blvd, College Station, TX 77845
- Texas A&M University, Physical Education Activity Program Building 4245, 632 Penberthy
  Blvd, College Station, TX 77843
- 503 George Bush Dr W, College Station, TX 77840
- Park West, 503 George Bush Dr W, College Station, TX 77840
- Olsen Field @ Blue Bell Park, 301 Olsen Blvd, College Station, TX 77840
- Rec Center, 187 Corrington Dr, College Station, TX 77843
- Kleberg, Kleberg Center, College Station, TX 77845
- MSC Bus Stop, College Station, TX 77840
Yell Practice:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel, A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Wehner, 4113 TAMU, College Station, TX 77845
- School of Public Health, 212 Adriance Lab Rd, College Station, TX 77843
- White Creek 1, 225 Discovery Dr, College Station, TX 77845
# - White Creek 2, 225 Discovery Dr, College Station, TX 77845
- Lot 101, 179 Discovery Dr, College Station, TX 77845
- NCTM, 100 Discovery Dr, College Station, TX 77845
- VTED, 800 Raymond Stotzer Pkwy, College Station, TX 77845
- Houston Building, 200 Discovery Dr, College Station, TX 77845
- White Creek Community Center, 667 W Campus Blvd, College Station, TX 77840
- School of Public Health, 212 Adriance Lab Rd, College Station, TX 77843
- Wehner, 4113 TAMU, College Station, TX 77845
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
