# I think we'd like for each stop to be in the format
# name, address
12th man:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel
- Wehner
- Vet School
- Transit
- Facilities Services
- GSC, 750 Agronomy Rd, College Station, TX 77840
- GSC, 750 Agronomy Rd, College Station, TX 77840
- Facilities Services - Inbound
- Transit - Inbound
- Lot 71
- Vet School - Inbound
- Wehner - Inbound
Bonfire:
- Commons, 676 Lubbock St, College Station, TX 77840
- Ross and Bizzell - North
- Ross and Ireland - North
- Asbury Water Tower
- Kleberg
- Rec Center
- Lot 100 G
- Reed Arena, 730 Olsen Blvd, College Station, TX 77843
- Reed Arena, 730 Olsen Blvd, College Station, TX 77843
- Kleberg - Inbound
- MSC - ILCB, 215 Lamar St, College Station, TX 77844
- Fish Pond, Military Walk, College Station, TX 77840
- Ross and Ireland (South)
- Ross and Bizzell (South)
- Southside Rec Center, 633 Bizzell St, College Station, TX 77843
- Lewis Street
Bush School:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Kleberg
- Reed Arena/Lot 97
- Ag Building
- GGB
- Bush School
- GERB
- Lot 108/UPD
- Technology Loop
- Lot 41/43
- Bush School 0 Inbound
- GGB
- Ag Building - Inbound
- Reed Arena, 730 Olsen Blvd, College Station, TX 77843
- Kleberg - Inbound
- MSC - ILCB, 215 Lamar St, College Station, TX 77844
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
Gig Em:
- Asbury Water Tower
- Fish Pond, Military Walk, College Station, TX 77840
- Ross and Ireland - South
- Ross and Bizzell - South
- Wisenbaker - East
- The Gardens
- Becky Gates Center, 1125 Hensel Dr, College Station, TX 77840
- Hensel @ Texas
- Zachry, 125 Spence St, College Station, TX 77843
- Ross and Bizzell - North
- Ross and Ireland - North
- Asbury Water Tower
Howdy:
- MSC Bus Stop, College Station, TX 77840
- A.P. Beutel Health Center, 311 Houston St Bldg. 520, College Station, TX 77843
- Kleberg Center, College Station, TX 77845
- 420 John Kimbrough Blvd, College Station, TX 77845
- Texas A&M University, Physical Education Activity Program Building 4245, 632 Penberthy
  Blvd, College Station, TX 77843
- 503 George Bush Dr W, College Station, TX 77840
- Park West, 503 George Bush Dr W, College Station, TX 77840
- Olsen Field @ Blue Bell Park
- Rec Center
- Kleberg - Inbound
Yell Practice:
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
- Beutel
- Wehner
- School of Public Health
- White Creek 1
- White Creek 2
- Lot 101
- NCTM, 100 Discovery Dr, College Station, TX 77845
- VTED
- Houston Building
- White Creek Community Center
- School of Public Health - Inbound
- Wehner - Inbound
- MSC, 275 Joe Routt Blvd, College Station, TX 77840
